### PR TITLE
Added Telegram link and alphabetized list of apps that use these emojis.

### PR DESCRIPTION
**Pull request by marknoble**

### CODE REVIEW

**Comment by Walkman100** [comment]
:+1:

**Comment by arvida** [comment]
Please put the link last in the list of services. 

I don't think there is any need to make the list alphabetized right now, it just makes it harder for people to add links. It is easier just to just append links to the list. This might not be the best solution but it works for now.

**Comment by marknoble** [comment]
As a site visitor I want the list of supported software alphabetized so the list is skimmable.

While the current randomized list is fine for users who aren't looking to see if their favorite app is listed, it's cumbersome for site visitors who know what they're looking for.

As the list grows, it could even result in duplicate listings.

While it does require that people adding links know the alphabet, more people will be viewing the site than contributing to it, so it makes sense to switch to an alphabetized list - especially since someone already donated their time to get the ball rolling in the right direction. :)

**Comment by arvida** [comment]
I see your points :+1: 

This touches on some things I have been thinking about on how to make the site more useful and easy to contribute to in the future. 

One of the things I would like to do is to move the ”data” (list of services and emojis) to multiple JSON files (maybe there is a better format for this?) that is used to build site on deploy and such. Maybe these JSON files should also be publicly available for other people to consume. Like a super simple API with the emojis and meta data. I think these files would be more easy to edit for contributors as well.

The other thing is how do people actually use the service list. Its quite long now and not easy to digest. Should it be searchable? Why do people actually look at it? Maybe it can be designed to be easily skimmable and actually usable? Should it be categoriezed? Whats good for the services listed?

Also I think these changes requires a update to the text on the web site.

I haven't had the time to move forward on these things yet, hope to do soon. 

So, I think this is a good idea but I wont merge this PR right now. I would like to put some more thought into this. Maybe sounds slow but I am very low on time right now. If you want the Telegram link on the emoji-cheat-sheet.com today do a separate PR. I will merge it and put it online tonight.

Sorry for a late reply!

**Pull request closed without merging**
