### PR TITLE
Rename moon to crescent_moon

### PR DESCRIPTION
**Pull request by fotos**
According to [Unicode 7.0](http://www.unicode.org/charts/PDF/Unicode-7.0/U70-1F300.pdf) and [this data list](http://www.unicode.org/Public/emoji/1.0/emoji-data.txt) there is no codepoint named `moon`. Instead `:moon:` should be renamed to `:crescent_moon:` (which is what this PR does).

Some libraries have aliased `:moon:`. Here is a short-list for a couple of them:

1. [gemoji](https://github.com/github/gemoji/) aliases`:moon:` to [`:waxing_gibbous_moon:`](https://github.com/github/gemoji/blob/master/db/emoji.json#L2773) (used by GH?)
2. [emojise](https://github.com/pepibumur/emojize/) also provides `:moon:` as the [`:waxing_gibbous_moon:`](https://github.com/pepibumur/emojize/blob/master/src/com/ppi/emoji/emojiParser.java#L959)
3. [rails-emoji](https://github.com/jsw0528/rails_emoji/) displays `:moon:` as the [`:crescent_moon:`](https://github.com/jsw0528/rails_emoji/blob/master/vendor/assets/images/emojis/moon.png) (most likely I should open a PR there too)
4. [twemoji](https://github.com/twitter/twemoji) AFAICS avoids this alltogether by only translating the Unicode codepoints

Providing a `data-alternative-name` for `moon` is not necessary since the JS uses `indexOf()` which finds all occurrences of `moon`.

IMHO the spec should explicitly name the "moon" but that's another (code)point.

### CODE REVIEW

**Comment by fotos** [comment]
[NSStringEmojize](https://github.com/diy/NSStringEmojize/) aliases `:moon:` to [`:waxing_gibbous_moon:`](https://github.com/diy/NSStringEmojize/blob/master/NSStringEmojize/emojis.h#L482) as well.

**Comment by Walkman100** [comment]
GH `:moon:`: :moon:

**Comment by peter76111** [comment]
2015-04-03 20:48 GMT+01:00, ░▒▓█│【Walkman】│█▓▒░ <notifications@github.com>:

**Comment by fotos** [comment]
@arvida is something blocking this? Can you provide some feedback?

**Comment by arvida** [comment]
Sorry for the delay :blush: 

Sounds like a good idea. Thanks!

**Pull request merged**
